# Generated by Django 4.1.1 on 2023-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='num_of_updates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='updatedby',
            field=models.CharField(default='default_value', max_length=200),
        ),
    ]
